/**
 * Mock data — real estate pilot client (PropNest Realty).
 * Replaced by Supabase queries when wired.
 */
import type { Lead, WAMessage, MetricCardData, AnalyticsData } from "./types";

export const mockMetrics: MetricCardData[] = [
  { label: "Active Leads", value: "52", delta: "+18%", deltaDirection: "up", color: "blue" },
  { label: "Qualified (Week)", value: "21", delta: "+15%", deltaDirection: "up", color: "green" },
  { label: "AI Conversations", value: "89", delta: "92% automated", color: "amber" },
  { label: "Assigned to Agents", value: "34", delta: "+11%", deltaDirection: "up", color: "purple" },
];

export const mockLeads: Lead[] = [
  {
    id: "ld_001",
    name: "Rachel Ng",
    company: "First-time buyer",
    email: "rachel.ng@gmail.com",
    phone: "+6591234567",
    status: "qualified_hot",
    score: 88,
    source: "meta_facebook",
    industry: "real_estate",
    createdAt: "2026-04-11T09:12:00Z",
    summary: "First-time buyer, pre-approved for $1.2M, looking for 3-bed condo in District 15 (East Coast). Wants to move within 3 months.",
    formAnswers: { intent: "Buy", property_type: "Private Condo", budget: "$1M - $2M", location: "East Coast / District 15", timeline: "Within 3 months", financing: "Yes, pre-approved" },
    dealValue: 1500000,
  },
  {
    id: "ld_002",
    name: "Kevin Tay",
    company: "Upgrader",
    email: "kevin.tay@outlook.com",
    status: "qualified_warm",
    score: 72,
    source: "meta_instagram",
    industry: "real_estate",
    createdAt: "2026-04-11T07:40:00Z",
    summary: "Selling HDB in Toa Payoh, upgrading to EC in Tengah. Budget $800k-1M. Financing in progress.",
    formAnswers: { intent: "Buy", property_type: "EC (Executive Condo)", budget: "$500k - $1M", location: "Tengah / Jurong", timeline: "3-6 months", financing: "In progress" },
    dealValue: 900000,
  },
  {
    id: "ld_003",
    name: "Amanda Chew",
    company: "Investor",
    status: "qualified_warm",
    score: 68,
    source: "google",
    industry: "real_estate",
    createdAt: "2026-04-11T06:15:00Z",
    summary: "Property investor looking for rental yield. Interested in 1-2 bed condos near MRT. Budget $1-2M.",
    formAnswers: { intent: "Buy", property_type: "Private Condo", budget: "$1M - $2M", location: "Near MRT stations", timeline: "3-6 months", financing: "Yes, pre-approved" },
    dealValue: 1200000,
  },
  {
    id: "ld_004",
    name: "Jason Lim",
    company: "Seller",
    status: "assigned",
    score: 78,
    source: "meta_facebook",
    industry: "real_estate",
    createdAt: "2026-04-10T14:30:00Z",
    summary: "Selling 4-room HDB in Bishan. Bought in 2018, MOP cleared. Looking for quick sale.",
    formAnswers: { intent: "Sell", property_type: "HDB", budget: "N/A", location: "Bishan", timeline: "Within 3 months", financing: "N/A" },
  },
  {
    id: "ld_005",
    name: "Diana Ong",
    company: "Renter",
    status: "nurture",
    score: 45,
    source: "tiktok",
    industry: "real_estate",
    createdAt: "2026-04-11T05:22:00Z",
    formAnswers: { intent: "Rent", property_type: "Private Condo", budget: "Below $500k", location: "CBD area", timeline: "Just exploring" },
  },
  {
    id: "ld_006",
    name: "Michael Tan",
    company: "HDB buyer",
    status: "contacted",
    score: 62,
    source: "meta_facebook",
    industry: "real_estate",
    createdAt: "2026-04-10T22:10:00Z",
    formAnswers: { intent: "Buy", property_type: "HDB", budget: "$500k - $1M", location: "Punggol / Sengkang", timeline: "Within 3 months", financing: "In progress" },
  },
  {
    id: "ld_007",
    name: "Sarah Lee",
    company: "Luxury buyer",
    status: "won",
    score: 95,
    source: "google",
    industry: "real_estate",
    createdAt: "2026-04-05T10:00:00Z",
    summary: "Purchased landed property in District 10. $4.8M deal closed.",
    formAnswers: { intent: "Buy", property_type: "Landed", budget: "Above $5M", location: "District 10", timeline: "Within 3 months", financing: "Yes, pre-approved" },
    dealValue: 4800000,
  },
  {
    id: "ld_008",
    name: "Vincent Goh",
    status: "new",
    score: 0,
    source: "meta_instagram",
    industry: "real_estate",
    createdAt: "2026-04-11T11:30:00Z",
  },
  {
    id: "ld_009",
    name: "Priya Nair",
    company: "Investor",
    status: "in_progress",
    score: 74,
    source: "meta_facebook",
    industry: "real_estate",
    createdAt: "2026-04-09T08:20:00Z",
    summary: "Looking for 2-bed condo for rental investment. Has 2 existing properties.",
    formAnswers: { intent: "Buy", property_type: "Private Condo", budget: "$1M - $2M", location: "Novena / Newton", timeline: "3-6 months", financing: "Yes, pre-approved" },
    dealValue: 1350000,
  },
  {
    id: "ld_010",
    name: "Raj Kumar",
    email: "raj@email.com",
    status: "disqualified",
    score: 22,
    source: "tiktok",
    industry: "real_estate",
    createdAt: "2026-04-11T04:01:00Z",
    formAnswers: { intent: "Rent", property_type: "HDB", budget: "Below $500k", timeline: "Just exploring", financing: "Not yet" },
  },
];

export const mockMessages: Record<string, WAMessage[]> = {
  ld_001: [
    {
      id: "m1", leadId: "ld_001", direction: "inbound", senderType: "lead",
      messageType: "text", body: "Hi, I saw your listing for East Coast condos. What's available in the $1-1.5M range?",
      createdAt: "2026-04-11T09:12:00Z",
    },
    {
      id: "m2", leadId: "ld_001", direction: "outbound", senderType: "ai",
      messageType: "text",
      body: "Hi Rachel! Thanks for reaching out. I'm Ava from PropNest Realty. Let me ask a few quick questions to match you with the right agent. Are you looking to buy, sell, or rent?",
      createdAt: "2026-04-11T09:12:15Z",
    },
    {
      id: "m3", leadId: "ld_001", direction: "inbound", senderType: "lead",
      messageType: "interactive_button", body: "Buy",
      createdAt: "2026-04-11T09:12:30Z",
    },
    {
      id: "m4", leadId: "ld_001", direction: "outbound", senderType: "ai",
      messageType: "interactive_list",
      body: "Great! What type of property are you looking for?",
      createdAt: "2026-04-11T09:12:35Z",
    },
    {
      id: "m5", leadId: "ld_001", direction: "inbound", senderType: "lead",
      messageType: "interactive_list", body: "Private Condo",
      createdAt: "2026-04-11T09:12:50Z",
    },
    {
      id: "m6", leadId: "ld_001", direction: "outbound", senderType: "ai",
      messageType: "interactive_list",
      body: "Nice! What's your budget range?",
      createdAt: "2026-04-11T09:12:55Z",
    },
  ],
};

export const mockPipelineColumns = [
  { stage: "new", label: "New", count: 8, value: 0 },
  { stage: "qualified", label: "Qualified", count: 12, value: 14500000 },
  { stage: "proposal", label: "Viewing", count: 6, value: 8200000 },
  { stage: "negotiation", label: "Negotiation", count: 4, value: 6300000 },
  { stage: "won", label: "Closed", count: 5, value: 9800000 },
];

export const mockAnalytics: AnalyticsData = {
  totalLeads: 312,
  qualifiedLeads: 108,
  qualificationRate: 34.6,
  avgScore: 56,
  leadsBySource: {
    meta_facebook: 124,
    meta_instagram: 78,
    google: 58,
    tiktok: 35,
    landing_page: 14,
    manual: 3,
  },
  leadsByStatus: {
    new: 15,
    qualifying: 8,
    qualified_hot: 18,
    qualified_warm: 28,
    nurture: 82,
    disqualified: 88,
    assigned: 24,
    contacted: 16,
    in_progress: 12,
    won: 16,
    lost: 5,
  },
  conversionFunnel: [
    { stage: "Leads In", count: 312 },
    { stage: "AI Qualified", count: 108 },
    { stage: "Assigned to Agent", count: 92 },
    { stage: "Viewing Booked", count: 64 },
    { stage: "Closed / Won", count: 16 },
  ],
  recentTrend: [
    { date: "Apr 5", leads: 42, qualified: 14 },
    { date: "Apr 6", leads: 38, qualified: 12 },
    { date: "Apr 7", leads: 51, qualified: 18 },
    { date: "Apr 8", leads: 45, qualified: 16 },
    { date: "Apr 9", leads: 48, qualified: 15 },
    { date: "Apr 10", leads: 52, qualified: 19 },
    { date: "Apr 11", leads: 36, qualified: 14 },
  ],
};
